name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: diegoquintanav/pelican-to-github-pages@v1.3.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
